# Generated by Django 6.0.6 on 2026-07-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='timezone',
            field=models.CharField(default='Asia/Krasnoyarsk', max_length=50, verbose_name='Часовой пояс'),
        ),
    ]
