# Generated by Django 6.0.6 on 2026-06-26 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('board_number', models.CharField(max_length=50, unique=True, verbose_name='Бортовой номер')),
                ('ktg_value', models.FloatField(default=1.0, verbose_name='КТГ')),
                ('ktg_threshold', models.FloatField(default=0.7, verbose_name='Порог КТГ')),
                ('is_in_repair', models.BooleanField(default=False, verbose_name='В ремонте')),
                ('image', models.ImageField(blank=True, null=True, upload_to='machines/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='KTGHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(verbose_name='Значение КТГ')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ktg_history', to='fleet.machine', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'История КТГ',
                'verbose_name_plural': 'История КТГ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='fleet.machine', verbose_name='Машина')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто отправил')),
            ],
            options={
                'verbose_name': 'Лог ремонта',
                'verbose_name_plural': 'Логи ремонтов',
                'ordering': ['-created_at'],
            },
        ),
    ]
