# Generated by Django 6.0.6 on 2026-07-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_machine_repair_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='ktg_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='КТГ обновлен'),
        ),
    ]
