# Generated by Django 6.0.6 on 2026-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_machine_ktg_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='ktg_updated_at',
        ),
        migrations.AddField(
            model_name='machine',
            name='ktg_reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Плановый сброс КТГ'),
        ),
    ]
