# Generated by Django 6.0.6 on 2026-07-06 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_remove_machine_ktg_updated_at_machine_ktg_reset_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='KTGMonthResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(verbose_name='Итоговый КТГ')),
                ('period_start', models.DateTimeField(verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(verbose_name='Конец периода')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ktg_results', to='fleet.machine', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Результат КТГ за период',
                'verbose_name_plural': 'Результаты КТГ за период',
                'ordering': ['-period_end'],
            },
        ),
    ]
