# Generated by Django 6.0.6 on 2026-07-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_ktgmonthresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='ktg_calc_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='КТГ считать от'),
        ),
    ]
