# Generated by Django 6.0.6 on 2026-07-09 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fleet', '0006_machine_ktg_calc_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='accounts.section', verbose_name='Участок'),
        ),
    ]
