# Generated by Django 6.0.6 on 2026-07-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_repairlog_repair_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='customer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_hours',
            field=models.FloatField(default=0, verbose_name='Моточасы'),
        ),
        migrations.AddField(
            model_name='machine',
            name='project_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер проекта'),
        ),
        migrations.AddField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='board_number',
            field=models.CharField(max_length=50, verbose_name='Бортовой номер'),
        ),
    ]
