# Generated by Django 6.0.6 on 2026-07-20 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_machine_customer_machine_engine_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineHoursLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(verbose_name='Моточасы')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_hours_log', to='fleet.machine', verbose_name='Машина')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто внёс')),
            ],
            options={
                'verbose_name': 'Лог моточасов',
                'verbose_name_plural': 'Лог моточасов',
                'ordering': ['-created_at'],
            },
        ),
    ]
